InsightSSG/Net-Manage

- collectors.py
- net-manage.ipynb
- parsers.py
- requirements.txt
- run_collectors.py
> Created nxos_get_vrfs collector

- collectors.py
- helpers.py
- net-manage.ipynb
- playbooks/f5_get_pools_and_members.yml
- playbooks/f5_get_vip_summary.yml
- run_collectors.py
- validators.py
> Issue 71: Update F5 validators to use optimized SQL query

- README.md
- helpers.py
- run_collectors.py
> Fixed Issue #82 - Output directory is not created

- collectors.py
- helpers.py
- run_collectors.py
> Created 'meraki_get_org_networks' collector

- collectors.py
- helpers.py
- run_collectors.py
> Add support for querying one or more Meraki organizations #86

- collectors.py
- helpers.py
> Add check for API enablement for Meraki collectors #90

- helpers.py
> Create function to read sqlite table schemas into a dataframe #92

- collectors.py
- helpers.py
> Create collector to get all Meraki devices in an organization #96

- collectors.py
- helpers.py
- net-manage.ipynb
- playbooks/f5_get_node_availability.yml
- run_collectors.py
- setup.py
> Function: F5 LTM: Create collector to get node availability #100

- collectors.py
- helpers.py
- run_collectors.py
> Pandas needs to be able to add new columns to existing tables #108

- collectors.py
- helpers.py
- net-manage.ipynb
- run_collectors.py
> Add option to filter by networks to 'meraki_get_org_device_statuses' collector #112

- collectors.py
- collectors/meraki_collectors.py
- helpers.py
- net-manage.ipynb
- run_collectors.py
- validators.py
> Create validator for Meraki device statuses #117

- collectors.py
- collectors/collectors.py
- helpers.py
- net-manage.ipynb
- run_collectors.py
- setup.py
- validators.py
closes #72 
closes #120 
closes #127
> Closes #72, #120, #127

- collectors/collectors.py
- requirements.txt
- validators.py
closes #131 
closes #132 
closes #133
> Resolves #131, #132, #133

- collectors/meraki_collectors.py
- helpers.py
- run_collectors.py
> Create collector to get LLDP neighbors on Meraki switches #137

- net-manage.ipynb
> Create collector to get port statuses on Meraki switches #136

- collectors/meraki_collectors.py
- helpers.py
- net-manage.ipynb
- run_collectors.py
> Create collector to get port usage on Meraki switches #140

- collectors/meraki_collectors.py
- helpers.py
- net-manage.ipynb
- run_collectors.py
- setup.py
closes #118 
closes #143 
closes #144 
closes #145 
Add collector to get status of all devices in Meraki networks #145
Fix missing 'meraki_map_network_to_organization' helpers function #144
Create collector to get clients from Meraki switches #143
Add functionality in meraki_device_statuses_availability validator to filter by organization #118
> Resolves issues 118, 143, 144, 145

- .gitignore
- collectors/meraki_collectors.py
- run_collectors.py
> Remove extra print statement from run_collectors #148

- helpers.py
> Docstring for helpers.get_user_meraki_input is incorrect #150

- collectors/collectors.py
- helpers.py
- parsers.py
- playbooks/palo_alto_get_security_rules.yml
- requirements.txt
- run_collectors.py
> Create collector to get inventory on Nexus 5000 and 7000 devices #160

- .gitignore
- collectors/infoblox_nios_collectors.py
- helpers.py
- net-manage.ipynb
- playbooks/cisco_ios_get_vlan_summary.yml
- requirements.txt
- run_collectors.py
- setup.py
> Create collector to get Infoblox NetworkContainers #164

- helpers.py
- run_collectors.py
> Create collector to map NIOS networks to containers #169

- collectors/infoblox_nios_collectors.py
- helpers/helpers.py
- helpers/netbox_helpers.py
- run_collectors.py
> Create Infoblox collector to get VLAN ranges #180

- collectors/infoblox_nios_collectors.py
- helpers/helpers.py
- run_collectors.py
> Create Infoblox collector to get VLANs #179

- collectors/infoblox_nios_collectors.py
closes #184 - Add support for validating certs to Infoblox NIOS collectors
closes #185 - Re-write infoblox_nios_collectors docstrings to use Numpy format
> Resolves #184 and #185

- helpers/helpers.py
> Create a helper function to get the timestamp of directory contents #192

- helpers/helpers.py
> Move update_ouis to helpers and split into two functions #191

- collectors/palo_alto_collectors.py
- connectors/palo_alto_connectors.py
closes #188 
closes #190 
closes #195
> Resolving #188, #190, #195

- .gitignore
- collectors/collectors.py
- collectors/palo_alto_collectors.py
- connectors/palo_alto_connectors.py
- helpers/helpers.py
- playbooks/palo_alto_get_arp_table.yml
- playbooks/palo_alto_get_logical_interfaces.yml
- playbooks/palo_alto_get_physical_interfaces.yml
- test/test_palo_alto_collectors.py
> Create unit tests for Palo Alto collectors #199

- requirements.txt
> Modify requirements.txt to install packages with pip #205

- .github/workflows/codeql.yml
- .github/workflows/dependency-review.yml
- .github/workflows/flake_lint.yml
- collectors/palo_alto_collectors.py
- test/test_palo_alto_collectors.py
> Resolves #204 and #208

- collectors/palo_alto_collectors.py
- helpers/helpers.py
- run_collectors.py
> panos logical interfaces not being added to database #211

- collectors/palo_alto_collectors.py
> panos arp table collector fails when arp table is empty #213

- helpers/helpers.py
- requirements.txt
> Resolves #224, #226

- collectors/collectors.py
- test/test_cisco_ios_collectors.py
- test/test_cisco_nxos_collectors.py
> Resolves #225 and #235

- playbooks/rw_cisco_nxos_delete_vlan.yml
- writers/cisco_nxos_writers.py
> Create writer to delete VLANs on Cisco Nexuses #249

- collectors/collectors.py
- net-manage.ipynb
- run_collectors.py
> Closes #251 and #253

- collectors/collectors.py
- run_collectors.py
> Cisco IOS arp_table collector fails #256

- collectors/collectors.py
> ios_get_cam_table collector fails #258

- collectors/solarwinds_collectors.py
- helpers/helpers.py
- run_collectors.py
> Resolves #270 and #271

- collectors/solarwinds_collectors.py
> Create function to get vendor for a Solarwinds NPM node #273

- collectors/solarwinds_collectors.py
- helpers/helpers.py
- net-manage.ipynb
- run_collectors.py
> Create collector to get all node serial numbers from Solarwinds NCM #284

- collectors/solarwinds_collectors.py
- helpers/helpers.py
- run_collectors.py
> Create collector to get all Solarwinds NPM node IDs #281

- collectors/solarwinds_collectors.py
- net_discovery_with_solarwinds.ipynb
> Create collector to get all container (group) data from Solarwinds NPM #288

- collectors/cisco_ios_collectors.py
- helpers/helpers.py
- run_collectors.py
> Create collector to get VRFs on Cisco IOS devices #294

- collectors/cisco_ios_collectors.py
- helpers/helpers.py
- playbooks/cisco_ios_gather_facts.yml
- run_collectors.py
> Resolves #298 and #299

- collectors/cisco_ios_collectors.py
- collectors/collectors.py
- collectors/palo_alto_collectors.py
- helpers/helpers.py
> Resolves #306 and #307

- collectors/meraki_collectors.py
- helpers/helpers.py
- net-manage.ipynb
- run_collectors.py
> Meraki collectors are failing #313

- collectors/meraki_collectors.py
> Add docstring and comments to network_appliance_vlans collector #320

- collectors/meraki_collectors.py
- collectors/netbox_collectors.py
- helpers/helpers.py
- requirements.txt
- test/test_palo_alto_collectors.py
closes #323 
closes #324 
closes #325 
closes #326
> Resolves #323, #324, #325, #326

- writers/netbox_writers.py
> Create writers file for Netbox #328

- collectors/netbox_collectors.py
> Create Netbox collector to get VRF details #330

- collectors/netbox_collectors.py
> Optimize netbox_get_vrf_details collector and add error checking #332

- writers/netbox_writers.py
> Create netbox writer to create a VRF #334

- writers/netbox_writers.py
> add_netbox_prefix writer is failing when VRF name is provided #336

- collectors/dnac_collectors.py
- helpers/helpers.py
- requirements.txt
> Create collector to get devices from Cisco DNAC #342

- collectors/dnac_collectors.py
- requirements.txt
> Create DNAC collector to get module details for all devices #344

- .gitignore
- collectors/dnac_collectors.py
- helpers/helpers.py
- helpers/report_helpers.py
- net-manage.ipynb
- reports/dnac_device_modules.py
- run_collectors.py
> Closes #346, #347

- .env_example
- collectors/dnac_collectors.py
- example_dot_env.env
- net-manage.ipynb
- requirements.txt
- run_collectors.py
> Modify net-manage.ipynb to use environment variables #348

- .env_example
- collectors/meraki_collectors.py
- helpers/helpers.py
- requirements.txt
- run_collectors.py
- writers/netbox_writers.py
> Closes #355, #356

- collectors/netbox_collectors.py
> Create Netbox collector for tenant attributes #357

- writers/netbox_writers.py
> Create Netbox writer to add a device type #359

- writers/netbox_writers.py
> Create Netbox writer to add or update a device role #361

- demos/dnac_device_modules.st.py
> Clean up comments in dnac_device_modules.st.py #366

- helpers/helpers.py
- net-manage.ipynb
- run_collectors.py
- setup.py
> Remove unused collectors import from net-manage.ipynb and setup.py #379

- collectors/meraki_collectors.py
- net-manage.ipynb
- run_collectors.py
- setup.py
- test/test_meraki_collectors.py
> Change meraki_get_network_clients collector to use meraki.aio #339

- collectors/meraki_collectors.py
- writers/netbox_writers.py
> Resolves #392, #393

- collectors/netbox_collectors.py
> Create function to get all interface attributes from Netbox #396

- netmanage/helpers/helpers.py
- netmanage/run_collectors.py
> Enable get security rules palo

- html/collectors/f5_collectors.html
- netmanage/collectors/f5_collectors.py
- playbooks/f5_get_node_availability.yml
- playbooks/f5_get_pool_availability.yml
- playbooks/f5_get_pool_data.yml
- playbooks/f5_get_pool_member_availability.yml
- playbooks/f5_get_pools_and_members.yml
- playbooks/f5_get_vip_availability_and_destination.yml
- playbooks/f5_get_vip_data.yml
- playbooks/f5_get_vip_pool_data.yml
- playbooks/f5_get_vip_summary.yml
- playbooks/f5_pre_post_checks.yml
> add recursive to f5 playbooks

- netmanage/run_collectors.py
- test/test_meraki_collectors.py
> Fix incorrect run_collectors import in test_meraki_collectors.py #408

- netmanage/__init__.py
- netmanage/collectors/cisco_ios_collectors.py
- netmanage/parsers/cisco_ios_parsers.py
> Split parsers from collectors

- demos/run_collectors.st.py
- netmanage/__init__.py
- netmanage/collectors/cisco_ios_collectors.py
- netmanage/collectors/cisco_nxos_collectors.py
- netmanage/parsers/cisco_ios_parsers.py
- netmanage/parsers/cisco_nxos_parsers.py
- test/test_cisco_ios_collectors.py
> Separate NXOS parsers

- netmanage/helpers/obfuscate_names.py
Updating the Name obfuscate to include the IP function from obfuscate_addresses. Searches all columns in all tables and converts the IPs.
> Updating the Name obfuscate to include the IP function

- netmanage/collectors/cisco_ios_collectors.py
- netmanage/collectors/cisco_nxos_collectors.py
- netmanage/collectors/solarwinds_collectors.py
- netmanage/helpers/helpers.py
- netmanage/helpers/solarwinds_helpers.py
- netmanage/parsers/cisco_ios_parsers.py
- netmanage/parsers/cisco_nxos_parsers.py
- netmanage/run_collectors.py
- standalone/ansible_inventory_from_solarwinds.py
- test/test_cisco_ios_collectors.py
- test/test_cisco_nxos_collectors.py
closes #490 
closes #492 
closes #493 
closes #494
> Resolve #490, #492, #493, #494
